In [4]:
import torch
import torch.nn as nn


In [5]:
x=torch.tensor([1.0,4.0],requires_grad=True)
y=(x**2).mean()
y.backward()
x.grad


tensor([1., 4.])

In [6]:
x.grad.zero_()
x.grad

tensor([0., 0.])

In [7]:
class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.Linear=nn.Linear(5,1)
        self.sigmoid=nn.Sigmoid()
    def forward(self,x):
        out =self.Linear(x)
        out=self.sigmoid(out)
        return out

In [8]:
model=Model()
x = torch.randn(3, 5)
output = model(x)
print("\nOutput:\n", output)



Output:
 tensor([[0.6406],
        [0.4954],
        [0.3708]], grad_fn=<SigmoidBackward0>)


In [ ]:
class Modell(nn.Module):
    def __init__(self):
        super().__init__()
        self.network=nn.Sequential(
            nn.Linear(5,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )

    def forward(self,z):
        out=self.network(z)
        return out0-

In [11]:
model=Modell()
z = torch.randn(3, 5)
output = model(z)
model.Linear1.weight
model.Linear1.bias

AttributeError: 'Modell' object has no attribute 'Linear1'