In [15]:
import torch
import torch.nn as nn
import torch.optim as optim

In [12]:
x=torch.tensor([1.0,4.0],requires_grad=True)
y=(x**2).mean()
y.backward()
x.grad


tensor([1., 4.])

In [13]:
x.grad.zero_()
x.grad

tensor([0., 0.])

In [ ]:
class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.Linear=nn.Linear(5,1)
        self.sigmoid=nn.Sigmoid()
    def forward(self,x):
        out =self.Linear(x)
        out=self.sigmoid(out)
        return out

In [29]:
model=Model()
x = torch.randn(3, 5)
output = model(x)
print("\nOutput:\n", output)



Output:
 tensor([[0.4872],
        [0.5050],
        [0.4028]], grad_fn=<SigmoidBackward0>)


In [36]:
class Modell(nn.Module):
    def __init__(self):
        super().__init__()
        self.network=nn.Sequential(
            nn.Linear(5,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )

    def forward(self,z):
        out=self.network(z)
        return out

In [37]:
model=Model()
x = torch.randn(3, 5)
output = model(x)
model.Linear1.weight
model.Linear1.bias

Parameter containing:
tensor([ 0.1191, -0.0734,  0.4349], requires_grad=True)