In [15]:
import torch
import torch.nn as nn
import torch.optim as optim

In [12]:
x=torch.tensor([1.0,4.0],requires_grad=True)
y=(x**2).mean()
y.backward()
x.grad


tensor([1., 4.])

In [13]:
x.grad.zero_()
x.grad

tensor([0., 0.])

In [25]:
class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.Linear=nn.Linear(5,1)
        self.sigmoid=nn.Sigmoid()
    def forward(self,x):
        out =self.Linear(x)
        out=self.sigmoid(out)
        return out

In [26]:
model=Model()
x = torch.randn(3, 5)
output = model(x)
print("\nOutput:\n", output)



Output:
 tensor([[0.3563],
        [0.4382],
        [0.3142]], grad_fn=<SigmoidBackward0>)
